image: fedora:rawhide

variables:
  DEPENDENCIES: gcc gtk-doc pkgconfig(udev) pkgconfig(systemd) pkgconfig(gio-2.0) pkgconfig(gudev-1.0) systemd gtk3-devel
      make autoconf autoconf-archive automake libtool

build_stable:
  before_script:
    - dnf upgrade -y --nogpgcheck fedora-release fedora-repos*
    - dnf update -y && dnf install -y $DEPENDENCIES
  script:
    - CPPFLAGS='-D_FORTIFY_SOURCE=2' ./autogen.sh --disable-dependency-tracking --enable-gtk-doc --enable-gtk-tests
    - make
    - make check
    - make install

