image: fedora:rawhide

variables:
  DEPENDENCIES: make gcc gtk-doc pkgconfig(udev) pkgconfig(systemd) pkgconfig(gio-2.0) pkgconfig(gudev-1.0) systemd

build_stable:
  allow_failure: true
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES_STABLE
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make check
    - make install

